export const CLEAR_DB = `Truncate Table
      "user",
      "role_permissions_permission",
      "permission",
      "order_product",
      "order",
      "role",
      "site_users_user",
      "table",
      "room",
      "device",
      "wifi",
      "menu_item",
      "menu",
      "product_category",
      "product",
      "category",
      "event",
      "schedule",
      "payment",
      "site",
      "account" `;
